let shopItemsData = [
  {
    id: "fone",
    name: "adidas",
    price: 45,
    desc: "Cartoon Astronaut T-Shirts",
    img: "/img/products/f1.jpg",
  },
  {
    id: "ftwo",
    name: "adidas",
    price: 45,
    desc: "Cartoon Astronaut T-Shirts",
    img: "/img/products/f2.jpg",
  },
  {
    id: "fthree",
    name: "adidas",
    price: 45,
    desc: "Cartoon Astronaut T-Shirts",
    img: "/img/products/f3.jpg",
  },
  {
    id: "ffour",
    name: "adidas",
    price: 45,
    desc: "Cartoon Astronaut T-Shirts",
    img: "/img/products/f4.jpg",
  },
  {
    id: "ffive",
    name: "adidas",
    price: 45,
    desc: "Cartoon Astronaut T-Shirts",
    img: "/img/products/f5.jpg",
  },
  {
    id: "fsix",
    name: "adidas",
    price: 45,
    desc: "Cartoon Astronaut T-Shirts",
    img: "/img/products/f6.jpg",
  },
  {
    id: "fseven",
    name: "adidas",
    price: 45,
    desc: "Cartoon Astronaut T-Shirts",
    img: "/img/products/f7.jpg",
  },
  {
    id: "feiht",
    name: "adidas",
    price: 45,
    desc: "Cartoon Astronaut T-Shirts",
    img: "/img/products/f8.jpg",
  },
];
